version: '3'

services:
  fastapi:
    build:
      context: ../../
      dockerfile: ./code/deployment/api/Dockerfile.fastapi
    container_name: fastapi
    volumes:
      - ./code:/app/code
    ports:
      - "80:80"

  streamlit:
    build:
      context: ../../
      dockerfile: ./code/deployment/app/Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi


  # airflow-webserver:
  #   image: apache/airflow:2.7.2
  #   depends_on:
  #     - airflow-init
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__API__AUTH_BACKEND=airflow.authentication.basic
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins

  # airflow-scheduler:
  #   image: apache/airflow:2.7.2
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins

  # airflow-init:
  #   image: apache/airflow:2.7.2
  #   command: ["bash", "-c", "airflow db init"]
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins
  #   depends_on:
  #     - airflow-webserver
