# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install any necessary packages
RUN pip install streamlit requests

# Expose port 8501 to the outside world
EXPOSE 8501

# Run Streamlit when the container launches
CMD ["streamlit", "run", "code/deployment/app/streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]