# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy everything from the spot-out directory to /app
COPY ../../ /app

# Optional: Print contents for verification
RUN echo "Contents of /app:" && ls -la /app

# Install required packages
RUN pip install fastapi uvicorn scikit-learn==1.4.1.post1 pandas joblib seaborn matplotlib

# Expose port 80 to the outside world
EXPOSE 80

# Run the FastAPI server with Uvicorn
CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "80"]
