# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN echo "Contents of /app:" && ls -la /app
# Make sure to install seaborn and matplotlib for EDA
# RUN pip install fastapi uvicorn scikit-learn pandas joblib seaborn matplotlib
RUN pip install fastapi uvicorn scikit-learn==1.4.1.post1 pandas joblib seaborn matplotlib

# Expose port 80 to the outside world
EXPOSE 80

# Run the FastAPI server with Uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "80"]

